<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Address_address_line2</name>
   <tag></tag>
   <elementGuidId>bc3fbd39-b68d-4c50-ba2e-303aafa3e0c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inputAddress2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputAddress2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>957ac05a-a5cb-491b-b579-dda3e966e69e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4bd956c3-e6fe-40f1-90da-01d9d8d7b9f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full border border-gray-90 text-size-14 rounded mt-10 px-10 py-5</value>
      <webElementGuid>f06bd2ec-431c-479c-ba81-fdcbbe1f0844</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputAddress2</value>
      <webElementGuid>edf2eb05-e73a-44b7-b6c1-7027fb1532b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>address_line2</value>
      <webElementGuid>e8895725-e901-47d4-8748-f9b8040666fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Address 2</value>
      <webElementGuid>bc5c7ae3-e025-4bfc-b96b-15109da92b29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputAddress2&quot;)</value>
      <webElementGuid>f170df5d-cea0-4ef5-bb9b-a80c05d2dc67</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputAddress2']</value>
      <webElementGuid>41271bfb-e47b-46d9-a999-8cc145c77ec5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='seleniumform']/div[4]/div[2]/input</value>
      <webElementGuid>5fcd51e1-0c90-46b5-9480-75a6d4ff4fd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/input</value>
      <webElementGuid>6f650a52-1780-4765-8c3b-85afed7f72c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'inputAddress2' and @name = 'address_line2' and @placeholder = 'Address 2']</value>
      <webElementGuid>15ff4ab9-ea8c-4355-8c82-ceb77f23e104</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
