<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_---Currency---       Dollar      Pou_e54511</name>
   <tag></tag>
   <elementGuidId>3b4cfb80-ae7d-43ab-8543-5f7997a63baf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#currency</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='currency']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>9dc39649-8dc4-4355-8e69-cc3ddbe37382</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-untouched ng-invalid ng-invalid-required</value>
      <webElementGuid>91ec433f-c558-4226-a02b-2ac6533ba617</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>currency</value>
      <webElementGuid>fd92d9ec-416b-483c-90d7-164914317584</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>currency</value>
      <webElementGuid>7bb247cf-2562-48e9-9198-1f0c5b33e6a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>currency</value>
      <webElementGuid>65b5b260-0abe-45c4-a2d7-72b7ccd111b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
	      		---Currency--- 
	      		Dollar
	      		Pound 
	      		Rupee
	    	</value>
      <webElementGuid>443eee2e-f940-439f-ac4b-f4d6ce248deb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;currency&quot;)</value>
      <webElementGuid>b0aeb414-f987-44ef-b62d-e50a06a1fba0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='currency']</value>
      <webElementGuid>74adb970-4449-4917-be6c-b1e6c82a28e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Currency :'])[1]/following::select[1]</value>
      <webElementGuid>b55269d1-fd95-4b4e-81e0-c19f6da3b40f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer :'])[1]/following::select[2]</value>
      <webElementGuid>de817575-8a23-483e-8d84-9caf331772f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Process'])[1]/preceding::select[1]</value>
      <webElementGuid>ece0968b-112e-471c-a821-d543c1b1b573</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'currency', '&quot;', ')')])[1]/preceding::select[1]</value>
      <webElementGuid>eaacfdf6-eaca-4809-8386-0002211bec25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/select</value>
      <webElementGuid>bad2c996-d227-4e1d-b228-f0e16842d208</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'currency' and @id = 'currency' and (text() = '
	      		---Currency--- 
	      		Dollar
	      		Pound 
	      		Rupee
	    	' or . = '
	      		---Currency--- 
	      		Dollar
	      		Pound 
	      		Rupee
	    	')]</value>
      <webElementGuid>7d1a35f4-f091-4609-91e2-623ac528b7ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
